import 'package:flutter/material.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedNotificationWidget5.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedRectangle5Widget3.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedVectorWidget27.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedOptionsWidget1.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedGroup3Widget2.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge6widget/generated/GeneratedVectorWidget28.dart';

/* Frame Android Large - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 360.0,
                height: 157.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -321.50,
                    z: 0,
                    child: GeneratedRectangle4Widget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 343.0,
                height: 26.0,
                child: TransformHelper.translate(
                    x: -1.50,
                    y: -380.00,
                    z: 0,
                    child: GeneratedNotificationWidget5()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 314.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -16.00,
                    y: -326.50,
                    z: 0,
                    child: GeneratedOptionsWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: TransformHelper.translate(
                    x: -118.00,
                    y: -166.00,
                    z: 0,
                    child: GeneratedRectangle5Widget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 332.0,
                height: 440.0,
                child: TransformHelper.translate(
                    x: -2.00, y: 4.00, z: 0, child: GeneratedGroup11Widget()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06943936347961426;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      24.998170852661133;

                  double percentHeight = 0.0312530517578125;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.00244140625;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4666666666666667,
                        translateY: constraints.maxHeight * 0.8525,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget27())
                  ]);
                }),
              ),
              Positioned(
                left: -32.857177734375,
                top: 441.1428527832031,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedSearchWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04033801555633545;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      14.521685600280762;

                  double percentHeight = 0.010294281244277954;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      8.235424995422363;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8777777777777778,
                        translateY: constraints.maxHeight * 0.1775,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget28())
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 318.9999084472656,
                height: 34.0,
                child: TransformHelper.translate(
                    x: -2.50,
                    y: -278.00,
                    z: 0,
                    child: GeneratedGroup3Widget2()),
              )
            ]),
      ),
    ));
  }
}
