import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge2widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge2widget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge2widget/generated/GeneratedUsericonWidget1.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge2widget/generated/GeneratedEmailpasswordWidget1.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge2widget/generated/GeneratedLoginButtonWidget1.dart';

/* Frame Android Large - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 430.0,
                height: 349.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -225.50,
                    z: 0,
                    child: GeneratedRectangle1Widget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 322.03076171875,
                height: 495.97125244140625,
                child: TransformHelper.translate(
                    x: 0.02,
                    y: 44.99,
                    z: 0,
                    child: GeneratedEmailpasswordWidget1()),
              ),

              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 85.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -0.50,
                    y: -291.00,
                    z: 0,
                    child: GeneratedUsericonWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 196.0,
                height: 61.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 281.50,
                    z: 0,
                    child: GeneratedLoginButtonWidget1()),
              )
            ]),
      ),
    ));
  }
}
