import 'package:flutter/material.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge3widget/generated/GeneratedOptionsWidget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge3widget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge3widget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge3widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge3widget/generated/GeneratedNotificationWidget4.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge3widget/generated/GeneratedRectangle4Widget.dart';

/* Frame Android Large - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
          child: Container(
            width: 360.0,
            height: 800.0,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 255, 255, 255),
                    ),
                  ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 435.0,
                        height: 157.0,
                        child: TransformHelper.translate(
                            x: 0.00,
                            y: -321.50,
                            z: 0,
                            child: GeneratedRectangle4Widget()),
                      ),

                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 314.0,
                        height: 90.23542785644531,
                        child: TransformHelper.translate(
                            x: -31.00,
                            y: -314.88,
                            z: 0,
                            child: GeneratedOptionsWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 430.0,
                        height: 483.0,
                        child: TransformHelper.translate(
                            x: -0.50, y: 23.50, z: 0, child: GeneratedGroup5Widget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 377.857177734375,
                        height: 479.00244140625,
                        child: TransformHelper.translate(
                            x: -23.93, y: 131.50, z: 0, child: GeneratedGroup7Widget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 318.9999084472656,
                        height: 34.0,
                        child: TransformHelper.translate(
                            x: -11.50, y: -278.00, z: 0, child: GeneratedGroup3Widget1()),
                      ),
                ]),

          ),
    ),
    );
  }
}
