import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge5widget/generated/GeneratedNotificationWidget7.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge5widget/generated/GeneratedOptionsWidget3.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge5widget/generated/GeneratedGroup12Widget.dart';

/* Frame Android Large - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 360.0,
                height: 157.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -321.50,
                    z: 0,
                    child: GeneratedOptionsWidget3()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 343.0,
                height: 26.0,
                child: TransformHelper.translate(
                    x: -0.50,
                    y: -379.00,
                    z: 0,
                    child: GeneratedNotificationWidget7()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 332.0,
                height: 440.0,
                child: GeneratedGroup12Widget(),
              )
            ]),
      ),
    ));
  }
}
