import 'package:flutter/material.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge4widget/generated/GeneratedNotificationWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge4widget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge4widget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge4widget/generated/GeneratedOptionsWidget2.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge4widget/generated/GeneratedGroup4Widget.dart';

/* Frame Android Large - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 255, 255, 255),
                    ),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 430.0,
                    height: 157.0,
                    child: TransformHelper.translate(
                        x: 0.00,
                        y: -321.50,
                        z: 0,
                        child: GeneratedOptionsWidget2()),
                  ),

                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 343.0,
                    height: 116.0,
                    child: TransformHelper.translate(
                        x: -0.50, y: -170.00, z: 0, child: GeneratedGroup8Widget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 343.0,
                    height: 264.0,
                    child: TransformHelper.translate(
                        x: 4.50, y: 35.00, z: 0, child: GeneratedGroup9Widget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 318.9999084472656,
                    height: 45.23542404174805,
                    child: TransformHelper.translate(
                        x: -7.50, y: -265.38, z: 0, child: GeneratedGroup4Widget()),
                  )
                ]),
          ),
        )
    );
  }
}
