import 'package:flutter/material.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedStudentidSCT19CS015Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedNotificationWidget2.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedNumberofBooksissued5Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/Generated1Widget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedAnoopSantoshWidget.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedUsericonWidget2.dart';
import 'package:flutterapp/digitallibraryapp/generatedandroidlarge7widget/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Android Large - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 360.0,
                height: 349.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -225.50,
                    z: 0,
                    child: GeneratedRectangle1Widget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 343.0,
                height: 26.0,
                child: TransformHelper.translate(
                    x: -1.50,
                    y: -380.00,
                    z: 0,
                    child: GeneratedNotificationWidget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 140.0,
                height: 138.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -242.00,
                    z: 0,
                    child: GeneratedUsericonWidget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 21.87744140625,
                height: 21.3232421875,
                child: TransformHelper.translate(
                    x: -156.06,
                    y: -330.34,
                    z: 0,
                    child: GeneratedVectorWidget12()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 313.0,
                height: 147.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: -21.50,
                    z: 0,
                    child: GeneratedRectangle9Widget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 279.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: 1.50,
                    y: -136.50,
                    z: 0,
                    child: GeneratedAnoopSantoshWidget()),
              ),
              Positioned(
                left: 50.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 42.0,
                child: GeneratedStudentidSCT19CS015Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 53.0,
                child: GeneratedNumberofBooksissued5Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 64.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08333333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.0375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7694444444444445,
                        translateY: constraints.maxHeight * 0.62625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget13())
                  ]);
                }),
              ),
              Positioned(
                left: 279.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 21.0,
                child: Generated1Widget(),
              )
            ]),
      ),
    ));
  }
}
